# Copyright 2014 Alvaro J. Genial [http://alva.ro]; see LICENSE file for more.

language: haskell

ghc:
  - 7.4
  - 7.6

install:
  - cabal install --only-dependencies --enable-tests
  - cabal install hlint
  - export PATH=$HOME/.cabal/bin:$PATH

before_script:
  - hlint . -i 'Too strict if'
